Adding end of life notice for Sufia
projecthydra/sufia pull request #3181
Opened 2017-11-27 17:02 UTC by jeremyf

Based on conversations on Slack and through email, the community has
agreed that Sufia is end-of-life, but that decision may not be as
obvious to those outside the community's communication channels.

2017-11-27 17:10 UTC, jcoyne submitted a review, later dismissed

2017-11-27 17:11 UTC, jcoyne commented
Can we bring this up on the tech call before merging?

2017-11-27 17:11 UTC, jeremyf commented
@jcoyne Sounds like a good plan.

2017-11-27 18:06 UTC, mjgiarlo requested changes
Blocking merger of this PR 'til we discuss on Wednesday's tech call.

2017-11-27 18:07 UTC, mjgiarlo commented on README.md
> +# End of Life Notice
I wonder if we should replace pretty much everything in this README with this section so folks don't miss it.

2017-11-27 18:10 UTC, mjgiarlo commented on README.md
> +* [release notes on the bridge of Sufia to Hyrax](https://github.com/samvera/hyrax/releases/tag/v1.0.0.rc2)
Change to https://github.com/samvera/hyrax/releases/tag/v1.0.1

2017-11-27 18:12 UTC, mjgiarlo commented on README.md
> +* [release notes on the bridge of Sufia to Hyrax](https://github.com/samvera/hyrax/releases/tag/v1.0.0.rc2)
Can you also add a line below this one:

```markdown
* [release notes on the bridge of CurationConcerns to Hyrax](https://github.com/samvera/hyrax/releases/tag/v2.0.0)
```
❓

2017-11-29 17:06 UTC, jcoyne commented
Please ask the tech list if anyone objects to us considering  CC & Sufia EOL.  if no objections, then we can merge this.

2017-11-30 18:54 UTC, jeremyf commented
https://groups.google.com/forum/#!topic/samvera-tech/guEUaByL8Y0

2017-12-13 17:08 UTC, mjgiarlo requested changes
Looking good. Just a couple links to tweak. Thanks!

2017-12-13 17:08 UTC, mjgiarlo commented on README.md
> +* [release notes on the bridge of Sufia to Hyrax](https://github.com/samvera/hyrax/releases/tag/v1.0.0)
Can you change this to point at 1.0.1? We had to yank 1.0.0 because it was released from the wrong branch.

2017-12-13 17:08 UTC, mjgiarlo commented on README.md
> +* [planning notes on consolidation](https://wiki.duraspace.org/pages/viewpage.action?pageId=78161232))
This is on our old wiki. Can you link to https://wiki.duraspace.org/pages/viewpage.action?pageId=87461232 instead?

2018-03-26 06:11 UTC, mjgiarlo commented
@jeremyf Is this PR still relevant and worth updating?

2025-05-08 18:37 UTC, closed without merging